spring.application.name=discovery-server
server.port=8761

# Tell Eureka NOT to register itself with another Eureka Server 
# (since this IS the server, it shouldn't try to look for another one)
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false