server.port=8081

spring.application.name=product-service
spring.application.datasource.url=jdbc:postgresql://localhost:5432/productdb
spring.application.datasource.username=admin@123
spring.application.datasource.password=adimn@123
spring.application.datasource.jpa.hibernate.ddl-auto=update
spring.application.datasource.jpa.show-sql=true
spring.application.datasource.jpa.properties.hibernate.format_sql=true

eureka.client.service-url.defaultZone=http://localhost:8761/eureka


